#!/usr/bin/env sh

sudo yabai --load-sa
yabai -m signal --add event=dock_did_restart action="sudo yabai --load-sa"

yabai -m config external_bar all:45:0
# Set Paddings
 yabai -m config \
  top_padding 5 \
  bottom_padding 10 \
  left_padding 10 \
  right_padding 10 \
  window_gap 10

yabai -m config window_animation_duration 0.0 \
  window_animation_easing ease_out_quint

# Splitting Rules
yabai -m config split_ratio 0.50 \
  auto_balance off \

# New window spawns to the right if vertical split, or bottom if horizontal split
yabai -m config window_placement second_child

yabai -m config window_zoom_persist off \
  window_shadow float \
  window_opacity off

yabai -m config mouse_follows_focus off focus_follows_mouse off

# Color of the window --insert message and mouse_drag selection.
# The purpose is to provide a visual preview of the new window frame.
yabai -m config insert_feedback_color 0xff9dd274
 
# set mouse interaction modifier key (default: fn)
yabai -m config mouse_modifier fn
# set modifier + left-click drag to move window (default: move)
yabai -m config mouse_action1 move
# set modifier + right-click drag to resize window (default: resize)
yabai -m config mouse_action2 resize
# Drag and Drop of window into anther action
yabai -m config mouse_drop_action swap

# Spaces Setup
yabai -m config layout bsp
yabai -m config --space=5 stack

yabai -m rule --add space=1 label="Safari" app="Safari"
yabai -m rule --add space=2 label="Ghostty" app="^Ghostty$"
yabai -m rule --add space=5 label="Spotify" app="^Spotify$"

# Exclude problematic apps from being managed:
yabai -m rule --add app="^(Calculator|Software Update|Dictionary|VLC|System Settings|zoom.us|Photo Booth|Archive Utility|App Store|Alfred Preferences|Activity Monitor|Finder)$" manage=off
yabai -m rule --add label="Finder Popups" app="^Finder$" title="(Co(py|nnect)|Move|Info|Pref)" manage=off
yabai -m rule --add label="Safari Popups" app="^Safari$" title="^(General|(Tab|Password|Website|Extension)s|AutoFill|Se(arch|curity)|Privacy|Advance)$" manage=off
yabai -m rule --add label="About This Mac" app="System Information" title="About This Mac" manage=off

echo "yabai configuration loaded"

borders style=round width=4.0 hidpi=on active_color=0xF0CBA6F7 inactive_color=0xFF1e1e2e background_color=0xFF313244 &

echo "sketchyborders options set"
