#!/bin/bash

export PLUGIN_DIR="$CONFIG_DIR/plugins"
export ITEM_DIR="$CONFIG_DIR/items"
export FONT="JetBrainsMono Nerd Font Propo"

source "$CONFIG_DIR/colors.sh"

source "$CONFIG_DIR/bar.sh"
source "$CONFIG_DIR/defaults.sh"

# Left side
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"

# Center
source "$ITEM_DIR/media.sh"

# Right side (order: right to left)
source "$ITEM_DIR/calendar.sh"
source "$ITEM_DIR/weather.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/wifi.sh"
source "$ITEM_DIR/volume.sh"
source "$ITEM_DIR/memory.sh"
source "$ITEM_DIR/cpu.sh"

sketchybar --update

