#!/usr/bin/env sh
                         
#        _____     _________      
# __________(_)__________  /_____ 
# __  __ \_  /_  _ \  __  /_  __ \
# _  / / /  / /  __/ /_/ / / /_/ /
# /_/ /_//_/  \___/\__,_/  \____/ 
                                
#                      __            
#        __           /\ \           
#   ___ /\_\     __   \_\ \    ___   
# /' _ `\/\ \  /'__`\ /'_` \  / __`\ 
# /\ \/\ \ \ \/\  __//\ \L\ \/\ \L\ \
# \ \_\ \_\ \_\ \____\ \___,_\ \____/
#  \/_/\/_/\/_/\/____/\/__,_ /\/___/ 

#        _          _       
#  _ __ (_) ___  __| | ___      
# | '_ \| |/ _ \/ _` |/ _ \     github: https://github.com/ni3do
# | | | | |  __/ (_| | (_) |    dotfiles: https://github.com/ni3do/dotfiles
# |_| |_|_|\___|\__,_|\___/ 
                          


### Load colors and icons ###
. "$HOME/.config/sketchybar/colors.sh"  # Loads all defined colors
. "$HOME/.config/sketchybar/icons.sh"   # Loads all defined icons

### Store plugin and item directories in variables ###
ITEM_DIR="$HOME/.config/sketchybar/items"       # Directory where the items are configured
PLUGIN_DIR="$HOME/.config/sketchybar/plugins"   # Directory where all the plugin scripts are stored

### Define space click script ###
export SPACE_CLICK_SCRIPT="yabai -m space --focus \$SID 2>/dev/null"

### Define default font ###
FONT="SF Pro" # Needs to have Regular, Bold, Semibold, Heavy and Black variants

### Padding ###
PADDINGS=3          # All elements use this padidng (Wherever i didn't need it, I used negetive padding)
SEGMENT_SPACING=13  # The spacing between segments

### Setting up the general bar appearance and default values ###
sketchybar --bar     height=36                                                     \
                     corner_radius=0                                               \
                     border_width=0                                                \
                     margin=0                                                      \
                     blur_radius=0                                                 \
                     position=top                                                  \
                     padding_left=4                                                \
                     padding_right=4                                               \
                     color=$BASE                                              \
                     topmost=off                                                   \
                     sticky=on                                                     \
                     font_smoothing=off                                            \
                     y_offset=0                                                    \
                     notch_width=0                                                 \
                                                                                   \
           --default drawing=on                                                    \
                     updates=when_shown                                            \
                     label.font="FONT:Bold:13.0"                                   \
                     icon.font="$FONT:Bold:14.0"                                   \
                     icon.color=$ICON_COLOR                                        \
                     label.color=$LABEL_COLOR                                      \
                     icon.padding_left=$PADDINGS                                   \
                     icon.padding_right=$PADDINGS                                  \
                     label.padding_left=$PADDINGS                                  \
                     label.padding_right=$PADDINGS                                 \
                     background.padding_right=$PADDINGS                            \
                     background.padding_left=$PADDINGS                             \
                     background.height=26                              \
                     background.corner_radius=9                        \
                     background.padding_right=$PADDINGS                \
                     background.padding_left=$PADDINGS                 \

# ### Template for some elements ###
# sketchybar --add item           label_template left                                \
#            --set label_template icon.drawing=off                                   \
#                                 label.font="$FONT:Black:12.0"                      \
#                                 label.padding_right=5                              \
#                                 click_script="$PLUGIN_DIR/toggle_bracket.sh"       \
#                                 background.padding_left=$SEGMENT_SPACING           \
#                                 drawing=off                                        \

# ### Spaces themselves are this ###
# . "$ITEM_DIR/spaces.sh"


# Left
source "$ITEM_DIR/apple.sh"
source "$ITEM_DIR/spaces.sh"
source "$ITEM_DIR/front_app.sh"


source "$ITEM_DIR/time.sh"
source "$ITEM_DIR/battery.sh"
source "$ITEM_DIR/updates.sh"
source "$ITEM_DIR/ssd.sh"
source "$ITEM_DIR/mem.sh"
source "$ITEM_DIR/cpu.sh"

### Menu bar items ###
source "$ITEM_DIR/system.sh"

### If an update is avalible, update sketchybar when launched ##
sketchybar --update

### Notify when sketchybarrc is finished loading ##
echo "sketchybar configuation loaded.."
